# Generated by Django 4.2 on 2023-05-15 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation_INFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Number', models.CharField(default='', max_length=264, verbose_name='Phone no:')),
                ('TrxID', models.CharField(default='', max_length=264, verbose_name='TrxID:')),
                ('Additional_Notes', models.TextField(default='', verbose_name='Type some notes:')),
                ('Time_Of_Donate', models.DateTimeField(auto_now_add=True)),
                ('Donator_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
