# Generated by Django 4.2 on 2023-05-19 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(max_length=264, verbose_name='Give the Amount')),
                ('Phone', models.CharField(max_length=264, verbose_name='Phone NO')),
                ('TrxID', models.CharField(max_length=264, verbose_name='TrxID')),
                ('Notes', models.TextField(verbose_name='Say something')),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
