# Generated by Django 4.2 on 2023-05-10 10:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Donor_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_info',
            name='Additional_Notes',
            field=models.CharField(default='DEFAULT VALUE', max_length=140),
        ),
        migrations.AddField(
            model_name='donation_info',
            name='Donated_Amount',
            field=models.DecimalField(decimal_places=2, default='DEFAULT VALUE', max_digits=10),
        ),
        migrations.AddField(
            model_name='donation_info',
            name='Donation_Date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 10, 10, 32, 38, 771289, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation_info',
            name='Donor_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Donor_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
